name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Run tests
      run: |
        cd functions
        npm test --if-present

  deploy-to-firebase:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Build project
      run: |
        mkdir -p public
        cp -r src/* public/ || true
        echo "Build completed"

    - name: Deploy to Firebase
      run: |
        firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting,firestore,storage,functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
